def f()
q="Ghostbusters\n"
w="If there's something strange\nIn you neighborhood\n"
e="Who you gonna call\n"
r="If there's something weird\nAnd it don't look good\n"
t="I ain't afraid of no ghost\n"
z="If you're seeing things\nRunning through your head\n"
y="Who can you call\n"
u="An invisible man\nSleeping in your bed\n"
i="If you're all alone\nPick up the phone\nAnd call\n"
o="I here it likes the girls\n"
p="Yeah yeah yeah yeah\n"
x="Who ya gonna call\n"
c="Who can ya call\n"
s="If you've had a dose of a\nFreaky ghost baby\nYou better call\n"
d="Lemme tell ya something\nBustin' makes me feel good\n"
b="Don't get caught alone no no\n"
g="When it comes through your door\nUnless you just want some more\n"
h="I think you better call\n"
j="I can't hear you\n"
k="Louder\n"
l="\n"
puts q+w+e+q+r+e+q+l+t+t+l+z+y+q+u+e+q+l+t+t+l+e+q+i+q+l+t+o+t+p+l+x+q+l+s+q+l+d+l+t+t+l+b+l+q+l+g+h+q+l+x+q+l+x+q+l+h+q+l+x+q+l+j+x+q+l+k+q+l+x+q+l+c+q+l+x+q
end
f()