def f():
  c,y="Ghostbusters"," ghost"
  q,l,b=" gonna call"+"\n"+c," better call","I ain't afraid of no"+y
  a,d,e,w,s,g,h,j="Who ya"+q+"\n","Who you"+q,"I think you"+l+"\n"+c,"\n"+b+"\n"+b+"\n"," something"," through your "," yeah","If "
  f,k=d+"\n"+c,"there's"+s
  print string.join([
c,
j+k+" strange\nIn you neighborhood",
d,
j+k+" weird\nAnd it don't look good",
d,
w,
j+"you're seeing things\nRunning"+g+"head\nWho can you call",
c,
"An invisible man\nSleeping in your bed",
d,
w,
d,
j+"you're all alone\nPick up the phone\nAnd call",
c,
"",
b,
"I here it likes the girls",
b,
"Yeah"+h+h+h+"\n",
a,
j+"you've had a dose of a\nFreaky"+y+" baby\nYou"+l,
c,
"\nLemme tell ya"+s,
"Bustin' makes me feel good",
w,
"Don't get caught alone no no\n",
c,
"\nWhen it comes"+g+"door\nUnless you just want some more",
e,
"",
a,
a,
e,
"",
a,
"I can't hear you",
a,
"Louder",
c,
"",
a,
"Who can ya call",
c,
"",
a],"\n")[:-1]